# Binance Pump and Dump Alert Configuration

# Using Spot API with url set to https://api.binance.com/api/v3/ticker/price
# Using Futures API with url set to: https://fapi.binance.com/fapi/v1/ticker/price
apiUrl: https://api.binance.com/api/v3/ticker/price

# Intervals which are monitored. Add or remove intervals as you like.
chartIntervals:
  - 1s
  - 5s
  - 15s
  - 30s
  - 1m
  - 5m
  - 15m
  - 30m
  - 1h
  - 3h
  - 6h

# Values in % at which an alert is triggered. Ensure interval exists in chartIntervals as well.
outlierIntervals:
  "1s": 0.01
  "5s": 0.02
  "15s": 0.03
  "30s": 0.04
  "1m": 0.05
  "5m": 0.05
  "15m": 0.07
  "30m": 0.1
  "1h": 0.15
  "3h": 0.2
  "6h": 0.25

# Used for telegram bot updates

# Insert telegramToken obtained from @BotFather here
telegramToken: mySecretToken
# Insert Chat ID obtained from @get_id_bot here
telegramChatId: mySecretChatId
# Insert Chat ID for top pump dump alert, if left on `0` it'll send the message to telegram chat id
telegramAlertChatId: 0

# Useful Params

# Interval between each price extract from Binance REST API
extractInterval: 1s

# Watchlist only mode, if enabled, ONLY pairs in watchlist will be monitored
# E.g. 'ADAUSDT', 'ETHUSDT'
# watchlist:
#  - ADAUSDT
#  - ETHUSDT

# List the trading currency you are interested in. Other options include 'BUSD', 'BTC' , 'ETH'
pairsOfInterest:
  - USDT

# Feature params

# Determine whether to look at DUMPs
dumpEnabled: True

# Top Pump & Dump Feature Params

# Set to false if not interested in top pump info
topPumpEnabled: True
# Set to false if not interested in top dump info
topDumpEnabled: True
# Set to false if not interested in net movement of coins
additionalStatsEnabled: True
# Top X amount of coins shown in the interval report, adjust to show more or less within the timeframe
noOfReportedCoins: 5
# Intervals for top pump and dump to be sent, ensure its in chartIntervals + outlierIntervals as well
topReportIntervals:
  - "1h"
  - "3h"
  - "6h"

# Define your own bot emojis.
botEmoji: ! "\U0001F916" # ğŸ¤–
pumpEmoji: ! "\U0001F7E2" # ğŸŸ¢ or '\U0001F4C8' ğŸ“ˆ '\U0001F53C'ğŸ”¼
dumpEmoji: ! "\U0001F534" # ğŸ”´ or '\U0001F4C9' ğŸ“‰ '\U0001F53D'ğŸ”½
topEmoji: ! "\U0001F3C6" # ğŸ†
newsEmoji: ! "\U0001F4F0" # ğŸ“°

# Debug Params (Avoid touching it if there's no issues)

# If False we do not print unnecessary messages
debug: False
# Interval for clearing array to prevent MEM ERROR can handle up to 12h+ depending on system
resetInterval: 12h
# In the case of get price fail, this is the time delay before re-attempt
priceRetryInterval: 5s
# If telegram message fails to send, this is the time delay before re-attempt
telegramRetryInterval: 2s
# Disables checking and adding of new listing pairs
checkNewListingEnabled: True
