# Binance Pump and Dump Alert Configuration

# Using Spot API with url set to https://api.binance.com/api/v3/ticker/price
# Using Futures API with url set to: https://fapi.binance.com/fapi/v1/ticker/price
apiUrl: https://api.binance.com/api/v3/ticker/price

# Intervals which are monitored. Add or remove intervals as you like.
chartIntervals:
  - 1s
  - 5s
  - 15s
  - 30s
  - 1m
  - 5m
  - 15m
  - 30m
  - 1h
  - 3h
  - 6h

# Values in %  at which an alert is triggered. Ensure interval exists in chartIntervals as well.
outlierIntervals:
  "1s": 0.02
  "5s": 0.05
  "15s": 0.06
  "30s": 0.08
  "1m": 0.1
  "5m": 0.1
  "15m": 0.15
  "30m": 0.2
  "1h": 0.3
  "3h": 0.4
  "6h": 0.5

# Used for telegram bot updates

# Insert telegramToken obtained from @BotFather here
telegramToken: mySecretToken
# Insert Chat ID obtained from @get_id_bot here
telegramChatId: mySecretChatId
# Insert Chat ID for top pump dump alert, if left on `0` it'll send the message to telegramChatId
telegramAlertChatId: 0

# Useful Params

# Interval between each price extract from Binance REST API
extractInterval: 1s

# List the trading currency you are interested in. Other options include 'BUSD', 'BTC' , 'ETH'
pairsOfInterest:
  - USDT

# Optional Watchlist only mode
# E.g. 'ADAUSDT', 'ETHUSDT' # Note that if watchlist has pairs, ONLY pairs in watchlist will be monitored
# watchlist:
#   - ADAUSDT
#   - ETHUSDT

# Feature params

# Determine whether to look at DUMPs
dumpEnabled: True

# Top Pump & Dump Feature Params

# Set to false if not interested in top pump info
topPumpEnabled: True
# Set to false if not interested in top dump info
topDumpEnabled: True
# Set to false if not interested in net movement of coins
additionalStatsEnabled: True
# Top X amount of coins shown in the interval report, adjust to show more or less within the timeframe
noOfReportedCoins: 5
# Intervals for top pump and dump to be sent, ensure its in chartIntervals + outlierIntervals as well
tpdReportsIntervals:
  - "1h"
  - "3h"
  - "6h"

# Visual Params. Define your own bot emojis.
botEmoji: ! "\U0001F916" # ü§ñ
pumpEmoji: ! "\U0001F7E2" # üü¢ or '\U0001F4B9' üíπ
dumpEmoji: ! "\U0001F534" # üî¥ or '\U0001F4C9' üìâ
tdpaEmoji: ! "\U0001F3C6" # üèÜ
newListingEmoji: ! "\U0001F4F0" # üì∞

# Debug Params (Avoid touching it if there's no issues)

# If False we do not print unnecessary messages
debug: False
# Interval for clearing array to prevent MEM ERROR can handle up to 12h+ depending on system
resetInterval: 12h
# In the case of get price fail, this is the time delay before re-attempt
priceRetryInterval: 5s
# If telegram message fails to send, this is the time delay before re-attempt
telegramRetryInterval: 2s
# Disables checking and adding of new listing pairs
checkNewListingEnabled: True
# Initial buffer before we trigger TPDA. Prevents all 0% lack of data points
tpdInitialOffset: 5m
